language: python
python:
  - "3.5"
os:
  - linux
before_install:
  - sudo add-apt-repository ppa:teward/swig3.0 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libeigen3-dev
  # Installing swig
  # ---------------
  - sudo apt-get install -y swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
install:
  - pip install cython
  - pip install pyyaml
  - pip install jinja2
  - travis_wait pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
script: coverage run --source=robo -m unittest discover test -v
after_success: coveralls
